/**
 * generated by Xtext 2.12.0
 */
package edu.ustb.sei.mde.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class SmartContractSpecificationLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public SmartContractSpecificationLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String text(final EObject o) {
    return o.eClass().getName();
  }
}
