/**
 * generated by Xtext 2.12.0
 */
package edu.ustb.sei.mde.ui.contentassist;

import edu.ustb.sei.mde.ui.contentassist.AbstractSmartContractSpecificationProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SmartContractSpecificationProposalProvider extends AbstractSmartContractSpecificationProposalProvider {
}
