/**
 * generated by Xtext 2.12.0
 */
package edu.ustb.sei.mde.ide;

import edu.ustb.sei.mde.ide.AbstractSmartContractSpecificationIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SmartContractSpecificationIdeModule extends AbstractSmartContractSpecificationIdeModule {
}
