/**
 * generated by Xtext 2.12.0
 */
package edu.ustb.sei.mde.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import edu.ustb.sei.mde.SmartContractSpecificationRuntimeModule;
import edu.ustb.sei.mde.SmartContractSpecificationStandaloneSetup;
import edu.ustb.sei.mde.ide.SmartContractSpecificationIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SmartContractSpecificationIdeSetup extends SmartContractSpecificationStandaloneSetup {
  @Override
  public Injector createInjector() {
    SmartContractSpecificationRuntimeModule _smartContractSpecificationRuntimeModule = new SmartContractSpecificationRuntimeModule();
    SmartContractSpecificationIdeModule _smartContractSpecificationIdeModule = new SmartContractSpecificationIdeModule();
    return Guice.createInjector(Modules2.mixin(_smartContractSpecificationRuntimeModule, _smartContractSpecificationIdeModule));
  }
}
