/*
 * generated by Xtext 2.12.0
 */
package edu.ustb.sei.mde


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SmartContractSpecificationRuntimeModule extends AbstractSmartContractSpecificationRuntimeModule {
}
