/*
 * generated by Xtext 2.12.0
 */
package edu.ustb.sei.mde

import com.google.inject.Injector
import org.eclipse.emf.ecore.EPackage
import edu.ustb.sei.mde.smartContractSpecification.SmartContractSpecificationPackage
import org.eclipse.emf.mwe.utils.StandaloneSetup

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
 
 //platformUri = ""
class SmartContractSpecificationStandaloneSetup extends SmartContractSpecificationStandaloneSetupGenerated {

	def static void doSetup() {
		new SmartContractSpecificationStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
	
	override void register(Injector injector) {		
		if (!(EPackage.Registry.INSTANCE.containsKey("http://www.ustb.edu.cn/sei/mde/SmartContractSpecification"))) {
			EPackage.Registry.INSTANCE.put("http://www.ustb.edu.cn/sei/mde/SmartContractSpecification", SmartContractSpecificationPackage.eINSTANCE);
		}
		super.register(injector);
	}
}
