<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="smartContractSpecification" nsURI="http://www.ustb.edu.cn/sei/mde/SmartContractSpecification"
    nsPrefix="scs">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contract" eSuperTypes="#//NamedElement #//FieldContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parties" lowerBound="1"
        upperBound="-1" eType="#//Party" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="terms" upperBound="-1"
        eType="#//Term" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumTypes" upperBound="-1"
        eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assets" upperBound="-1"
        eType="#//Asset" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Party" abstract="true" eSuperTypes="#//NamedElement #//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexType" eSuperTypes="#//Type #//FieldContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Asset" eSuperTypes="#//Type #//FieldContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Field" eSuperTypes="#//NamedElement #//TypedElement #//DataSlot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="many" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//NamedElement #//TypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Field" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsMany" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Times" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="used" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalParty" abstract="true" eSuperTypes="#//Party #//DataSlot #//FieldContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingleParty" eSuperTypes="#//InternalParty"/>
  <eClassifiers xsi:type="ecore:EClass" name="GroupParty" eSuperTypes="#//InternalParty"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalParty" eSuperTypes="#//Party"/>
  <eClassifiers xsi:type="ecore:EClass" name="Term" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//Action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="party" eType="#//Party"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transferOperations" upperBound="-1"
        eType="#//TransferOperation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="break" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postCondition" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="breachOperations" upperBound="-1"
        eType="#//TransferOperation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RightTerm" eSuperTypes="#//Term"/>
  <eClassifiers xsi:type="ecore:EClass" name="DutyTerm" eSuperTypes="#//Term"/>
  <eClassifiers xsi:type="ecore:EClass" name="BreachTerm" eSuperTypes="#//Term"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionSourceExpression" abstract="true"
      eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="DescriptiveExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="plainText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuantifierExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" lowerBound="1" eType="#//CollectionSourceExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iterator" lowerBound="1"
        eType="#//IteratorDeclExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qunatifier" lowerBound="1"
        eType="#//Quantifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Quantifier">
    <eLiterals name="forAll"/>
    <eLiterals name="exists" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IteratorDeclExpression" eSuperTypes="#//DataSlot #//NamedElement">
    <eOperations name="getType" lowerBound="1" eType="#//FieldContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionExpression" abstract="true"
      eSuperTypes="#//Expression #//CollectionSourceExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//CollectionSourceExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectExpression" eSuperTypes="#//CollectionExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalExpression" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenBranch" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBranch" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplyExpression" eSuperTypes="#//LogicalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implied" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndExpression" eSuperTypes="#//LogicalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrExpression" eSuperTypes="#//LogicalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotExpression" eSuperTypes="#//LogicalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inner" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationalExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//RelationalOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RelationalOperator">
    <eLiterals name="equal"/>
    <eLiterals name="less" value="1"/>
    <eLiterals name="lessOrEqual" value="2"/>
    <eLiterals name="greater" value="3"/>
    <eLiterals name="greaterOrEqual" value="4"/>
    <eLiterals name="notEqual" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimePredicate" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//TimePredicateOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoundedTimePredicate" eSuperTypes="#//TimePredicate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bound" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="closed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PeriodicTimePredicate" eSuperTypes="#//TimePredicate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="period" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basefrom" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseto" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="periodDate" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimePredicateOperator">
    <eLiterals name="after"/>
    <eLiterals name="before" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeExpression" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeConstant" eSuperTypes="#//TimeExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="month" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="day" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hour" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sec" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeVarExpression" eSuperTypes="#//TimeExpression #//SlotRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActionEnforcedTimeQuery" eSuperTypes="#//TimeQuery">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="party" lowerBound="1" eType="#//Party"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" lowerBound="1"
        eType="#//PartyMemberMultiplicity" defaultValueLiteral="this"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PartyMemberMultiplicity">
    <eLiterals name="all"/>
    <eLiterals name="any" value="1"/>
    <eLiterals name="this" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TermValidTimeQuery" eSuperTypes="#//TimeQuery">
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" lowerBound="1" eType="#//Term"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalTimeQuery" eSuperTypes="#//TimeQuery #//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//TimeQueryOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeQuery" abstract="true" eSuperTypes="#//TimeExpression"/>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeQueryOperator">
    <eLiterals name="now"/>
    <eLiterals name="contractStart" value="1"/>
    <eLiterals name="contractEnd" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmeticExpression" abstract="true"
      eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditiveExpression" eSuperTypes="#//ArithmeticExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//AdditiveOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AdditiveOperator">
    <eLiterals name="add"/>
    <eLiterals name="sub" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiplicativeExpression" eSuperTypes="#//ArithmeticExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//MultiplicativeOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MultiplicativeOperator">
    <eLiterals name="mul"/>
    <eLiterals name="div" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantExpression" abstract="true"
      eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="FloatConstant" eSuperTypes="#//ConstantExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringConstant" eSuperTypes="#//ConstantExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerConstant" eSuperTypes="#//ConstantExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Valueconstant" eSuperTypes="#//ConstantExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;value&quot;"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Booleanconstant" eSuperTypes="#//ConstantExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeLib">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SlotRef" eSuperTypes="#//Expression #//CollectionSourceExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slot" eType="#//DataSlot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//SlotRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitive" lowerBound="1"
        eType="#//TransitiveOperator" defaultValueLiteral="none"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TransitiveOperator">
    <eLiterals name="none"/>
    <eLiterals name="transitiveEnclosure" value="1"/>
    <eLiterals name="selfTransitiveEnclosure" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSlot" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TransferOperation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="money" lowerBound="1" eType="#//MoneyExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deposit" eSuperTypes="#//TransferOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Withdraw" eSuperTypes="#//TransferOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transfer" eSuperTypes="#//TransferOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="account" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThisExpression" eSuperTypes="#//TimeExpression #//SlotRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="FieldContainer" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//Field" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeLine" eSuperTypes="#//TimeExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" eType="#//TimeExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviation" eType="#//TimeExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//TimeLineOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeLineOperator">
    <eLiterals name="forward"/>
    <eLiterals name="backward" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="enumType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="selections" lowerBound="1"
        upperBound="-1" eType="#//Selection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Selection" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="MoneyExpression" eSuperTypes="#//DataSlot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationOperator" eType="#//RelationalOperator"
        defaultValueLiteral="equal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RightExpression" eSuperTypes="#//DataSlot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RightType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RightProporty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
