/**
 * generated by Xtext 2.12.0
 */
package edu.ustb.sei.mde.validation;

import edu.ustb.sei.mde.validation.AbstractSmartContractSpecificationValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SmartContractSpecificationValidator extends AbstractSmartContractSpecificationValidator {
}
