/*
 * generated by Xtext 2.12.0
 */
package edu.ustb.sei.mde.ide


/**
 * Use this class to register ide components.
 */
class SmartContractSpecificationIdeModule extends AbstractSmartContractSpecificationIdeModule {
}
