/*
 * generated by Xtext 2.12.0
 */
package edu.ustb.sei.mde.ide

import com.google.inject.Guice
import edu.ustb.sei.mde.SmartContractSpecificationRuntimeModule
import edu.ustb.sei.mde.SmartContractSpecificationStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class SmartContractSpecificationIdeSetup extends SmartContractSpecificationStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new SmartContractSpecificationRuntimeModule, new SmartContractSpecificationIdeModule))
	}
}
