/**
 * generated by Xtext 2.12.0
 */
package edu.ustb.sei.mde.ui;

import com.google.inject.Binder;
import edu.ustb.sei.mde.ui.AbstractSmartContractSpecificationUiModule;
import edu.ustb.sei.mde.ui.HighlightingConfiguration;
import edu.ustb.sei.mde.ui.SpescAntlrTokenToAttributeIdMapper;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ide.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SmartContractSpecificationUiModule extends AbstractSmartContractSpecificationUiModule {
  @Override
  public void configure(final Binder binder) {
    super.configure(binder);
    binder.<IHighlightingConfiguration>bind(IHighlightingConfiguration.class).to(HighlightingConfiguration.class);
    binder.<AbstractAntlrTokenToAttributeIdMapper>bind(AbstractAntlrTokenToAttributeIdMapper.class).to(SpescAntlrTokenToAttributeIdMapper.class);
  }
  
  public SmartContractSpecificationUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
