/*
 * generated by Xtext 2.22.0
 */
package edu.ustb.sei.mde.ui;

import com.google.inject.Injector;
import edu.ustb.sei.mde.smartcontract.scs.ui.internal.ScsActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SmartContractSpecificationExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ScsActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ScsActivator activator = ScsActivator.getInstance();
		return activator != null ? activator.getInjector(ScsActivator.EDU_USTB_SEI_MDE_SMARTCONTRACTSPECIFICATION) : null;
	}

}
