/*
 * generated by Xtext 2.22.0
 */
package edu.ustb.sei.mde.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSmartContractSpecificationScopeProvider extends DelegatingScopeProvider {
}
