/**
 * generated by Xtext 2.12.0
 */
package edu.ustb.sei.mde;

import com.google.inject.Injector;
import edu.ustb.sei.mde.SmartContractSpecificationStandaloneSetupGenerated;
import edu.ustb.sei.mde.smartContractSpecification.SmartContractSpecificationPackage;
import org.eclipse.emf.ecore.EPackage;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmartContractSpecificationStandaloneSetup extends SmartContractSpecificationStandaloneSetupGenerated {
  public static void doSetup() {
    new SmartContractSpecificationStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
  
  @Override
  public void register(final Injector injector) {
    boolean _containsKey = EPackage.Registry.INSTANCE.containsKey("http://www.ustb.edu.cn/sei/mde/SmartContractSpecification");
    boolean _not = (!_containsKey);
    if (_not) {
      EPackage.Registry.INSTANCE.put("http://www.ustb.edu.cn/sei/mde/SmartContractSpecification", SmartContractSpecificationPackage.eINSTANCE);
    }
    super.register(injector);
  }
}
