/**
 * generated by Xtext 2.12.0
 */
package edu.ustb.sei.mde;

import edu.ustb.sei.mde.AbstractSmartContractSpecificationRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmartContractSpecificationRuntimeModule extends AbstractSmartContractSpecificationRuntimeModule {
}
